services:
  pay-crew2-postgres:
    container_name: pay-crew2-postgres
    image: postgres:latest
    volumes:
      - pay-crew2-postgres:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: pg_isready -U "${POSTGRES_USER}" || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pay-crew2-postgres:
    name: pay-crew2-postgres
