name: deploy-frontend

permissions:
  contents: read
  pull-requests: read

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      # Install Nix
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      # Build
      - name: Build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_CLIENT_URL: ${{ secrets.VITE_CLIENT_URL }}
          VITE_REDIRECT_URL: ${{ secrets.VITE_REDIRECT_URL }}
          VITE_IDENTEAPOT_SALT: ${{ secrets.VITE_IDENTEAPOT_SALT }}
        run: nix develop --command bash -c "pnpm i && pnpm run build"
      # Deploy Frontend to Cloudflare Workers
      - name: Deploy Frontend to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          wranglerVersion: "4.45.3"
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: "products/frontend"
